name: Build APK
on:
  push:
    branches:
      - build-android-app
  pull_request:
    branches:
      - build-android-app
      

jobs:
  build-android:
    name: Build for Android
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Cache build dependencies like pip, Buildozer, Gradle, and Android SDK
      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.buildozer
            ~/.cache/pip
            ~/.gradle/caches
            ~/.gradle/wrapper
            ~/.android
          key: ${{ runner.os }}-buildozer-cache
          restore-keys: |
            ${{ runner.os }}-buildozer-cache

      - name: Install Buildozer dependencies
        run: |
          sudo apt update
          sudo apt install -y git zip unzip python3-pip autoconf libtool pkg-config \
            zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake ccache \
            libffi-dev libssl-dev automake
          python3 -m pip install --user --upgrade Cython virtualenv
          python3 -m pip install --user --upgrade buildozer python-for-android

      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build APK with Buildozer
        run: |
          export PATH=$PATH:~/.local/bin
          cd src
          yes | buildozer -v android debug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: src/bin/*.apk
