name: Build Kivy App for Android

on:
  push:
    branches:
      - main  # Replace with your branch name
  pull_request:
    branches:
      - main  # Replace with your branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'  # Replace with the Python version you use

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential openjdk-8-jdk wget unzip ccache libssl-dev
        python -m pip install --upgrade pip
        pip install cython==0.29.36  # Ensure compatible version
        pip install kivy
        pip install buildozer

    - name: Install Android SDK and NDK
      run: |
        wget https://dl.google.com/android/repository/commandlinetools-linux-8092744_latest.zip -O cmdline-tools.zip
        mkdir -p $HOME/android-sdk/cmdline-tools/latest
        unzip -q cmdline-tools.zip -d $HOME/android-sdk/cmdline-tools/latest
        export ANDROID_SDK_ROOT=$HOME/android-sdk
        export PATH=$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$ANDROID_SDK_ROOT/platform-tools:$PATH
        echo "ANDROID_SDK_ROOT=$HOME/android-sdk" >> $GITHUB_ENV
        echo "PATH=$HOME/android-sdk/cmdline-tools/latest/bin:$HOME/android-sdk/platform-tools:$PATH" >> $GITHUB_ENV
        yes | $HOME/android-sdk/cmdline-tools/latest/bin/sdkmanager --install "platform-tools" "build-tools;30.0.3" "platforms;android-30"
        yes | $HOME/android-sdk/cmdline-tools/latest/bin/sdkmanager --licenses

    - name: Build Kivy app
      env:
        ANDROIDSDK: ${{ env.ANDROID_SDK_ROOT }}
        PATH: ${{ env.PATH }}
      run: |
        buildozer -v android debug

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: kivy-app-build
        path: ../build  # Path to your build output directory

    - name: Notify build status
      run: |
        echo "Build complete"
