name: Entweni

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Get Current Date
      - name: Get Date
        id: get-date
        run: |
          echo "date=$(date -u "+%Y%m%d")" >> $GITHUB_OUTPUT
        shell: bash

      # Cache Buildozer global directory
      - name: Cache Buildozer global directory
        uses: actions/cache@v4
        with:
          path: .buildozer_global
          key: buildozer-global-${{ hashFiles('buildozer.spec') }}

      # Cache Buildozer directory
      - name: Cache Buildozer directory
        uses: actions/cache@v4
        with:
          path: .buildozer
          key: ${{ runner.os }}-${{ steps.get-date.outputs.date }}-${{ hashFiles('buildozer.spec') }}

      # Cache Gradle dependencies
      - name: Cache Gradle dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper/
          key: gradle-${{ runner.os }}-${{ steps.get-date.outputs.date }}
          restore-keys: |
            gradle-${{ runner.os }}-

      # Install dependencies
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt-get install -y \
            build-essential git ffmpeg libsdl2-dev libsdl2-image-dev \
            libsdl2-mixer-dev libsdl2-ttf-dev libportmidi-dev libswscale-dev \
            libavformat-dev libavcodec-dev libunwind-dev zlib1g-dev \
            libsqlite3-dev sqlite3 bzip2 libbz2-dev openssl libgdbm-dev \
            libgdbm-compat-dev liblzma-dev libreadline-dev uuid-dev \
            libgstreamer1.0 gstreamer1.0-plugins-base gstreamer1.0-plugins-good \
            zip unzip autoconf libtool pkg-config libncurses5-dev \
            libncursesw5-dev libtinfo5 cmake libffi-dev libssl-dev automake

      # Set up Java 21 required by Gradle
      - name: Setup Java 21 required by Gradle
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'  # or 'zulu', 'liberica', etc.
          java-version: '21'

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12' #set your python version

      # Install pip dependencies
      - name: Install pip dependencies
        run: |
          pip install --upgrade pip
          pip install --upgrade buildozer Cython
        # pip install buildozer cython==0.29.33

      # Build with Buildozer
      - name: Build with Buildozer
        id: buildozer
        run: |
          yes | buildozer -v android debug | tee buildozer.log
        # buildozer -v android clean

      # Upload APK artifact
      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: bin/*.apk
